version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/discuss-idea
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  ApplicationStart:
    - location: .github/workflows/scripts/run
      timeout: 600
      runas: ubuntu