#!/bin/bash

NOW=$(date "+%Y-%m-%d-%m-%s")
CURRENT_DIR=$(pwd)

# Clean build files
function clean() {
  echo "Cleaning build files.."
  rm -rf ./build
}

if [ ! -d log ]; then
  echo "Log folder not exists. Creating log folder.."
  mkdir log
fi

clean
echo "Starting application.."
chmod +x gradlew
./gradlew run > "log/$NOW.log"

exit 0
