#!/bin/bash

NOW=$(date "+%Y-%m-%d-%m-%s")
CURRENT_DIR=$(pwd)

# Clean build files
function clean() {
  echo "Cleaning build files.."
  rm -rf ./build
}

if [ ! -d log ]; then
  echo "Log folder not exists. Creating log folder.."
  mkdir log
fi

clean

nohup java -jar ${PROJECT_DIR}/build/libs/*.jar > /home/ubuntu/nohup.out 2>&1 &

exit 0
